#deployments vem de apps/v1
apiVersion: apps/v1
#tipo
kind: Deployment
metadata:
  #nome do deployment
  name: app-deployment
spec:
#quantas cópias
  replicas: 1
  #para especificar o rótulo
  selector:
    matchLabels:
      #rótulo, app não tem nada de especial, pode ser qq coisa
      #Deploymevai selecionar todo Pod que tiver esse rótulo
      app: app
  #modelo qvai ser usado para construção dos Pods
  template:
    metadata:
      labels:
        #os Pods terão esse rótulo, assim,
        #serão selecionados por esse deployment
        app: app
    spec:
      containers:
        - name: app
          image: sistemasuprimento/app:0.0.1
          resources:
            limits:
              memory: 256Mi
              cpu: 1
